version: "3.9"

services:
  linkchecker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: linkchecker:latest
    container_name: linkchecker
    restart: unless-stopped

    environment:
      # GitHub cible
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_NAME: ${GITHUB_NAME}
      GITHUB_BRANCH: ${GITHUB_BRANCH:-main}
      INCLUDE_PATHS: ${INCLUDE_PATHS:-data/}

      # Réseau & contrôle
      HTTP_TIMEOUT_MS: ${HTTP_TIMEOUT_MS:-10000}
      HTTP_RETRIES: ${HTTP_RETRIES:-1}
      HTTP_CONCURRENCY: ${HTTP_CONCURRENCY:-12}
      ALLOWED_MIME_PREFIXES: ${ALLOWED_MIME_PREFIXES:-image/,video/}

      # Planif & logs
      TIMEZONE: ${TIMEZONE:-Europe/Paris}
      CRON_SCHEDULE: ${CRON_SCHEDULE:-0 9,21 * * *}
      REPORT_MODE: ${REPORT_MODE:-only-errors}
      REPORT_BATCH_SIZE: ${REPORT_BATCH_SIZE:-20}
      DRY_RUN: ${DRY_RUN:-1}
      RUN_ON_START: ${RUN_ON_START:-1}

      # ⚠️ Secrets en env (Standalone)
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}

    volumes:
      - linkchecker_state:/state

    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  linkchecker_state:
